colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
firebase = { }
fathomAnalytics = { }
verification = { }
defaultBackgroundImage = "featured.svg"
defaultFeaturedImage = "pattern.jpeg"

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "featured.svg"
showRecent = false
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = false
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editURL = "https://github.com/SubaruLenz/Budget-Tracker-Workshop"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [ "email", "facebook", "github", "steam", "whatsapp" ]

[list]
showBreadcrumbs = false
showSummary = false
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
